Grupo A
bismarckpm/UCABDWSEmpresa1_2022-2023 pull request #1
Opened 2022-11-07 00:15 UTC by joseyepes96

CRUD Requerimiento 9: Administrar Cargos

Revisar en UsuarioController y cambiar la conexión de la BD

2022-11-08 16:39 UTC, franlunar submitted a review, later dismissed
OK, sugiero hacer pull request un poco más cortos agregando solo una funcionalidad por vez

2022-11-09 16:35 UTC, ileido1 commented
Aprobado

2022-11-09 16:36 UTC, ileido1 submitted a review, later dismissed

2022-11-09 16:37 UTC, franlunar submitted a review, later dismissed

2022-11-09 23:55 UTC, franlunar requested changes
Merge a la rama equivocada

2022-11-09 23:58 UTC, myangui commented
Abriendo nuevamente, cambiando la rama destino a develop

2022-11-10 00:01 UTC, franlunar approved these changes, later dismissed

2022-11-10 00:02 UTC, myangui submitted a review, later dismissed

2022-11-18 22:03 UTC, closed without merging